import { z } from 'zod';

export const createEmployeeSchema = z.object({
  body: z.object({
    employeeCode: z.string().min(2),
    fullName: z.string().min(3),
    email: z.string().email(),
    phone: z.string().min(10),
    department: z.string().min(2),
    designation: z.string().min(2),
    joiningDate: z.string(),
    salary: z.number().min(0),
    address: z.string().min(5),
    password: z.string().optional(),
    profileImage: z.string().optional(),
    emergencyContact: z.object({
      name: z.string().min(2),
      relationship: z.string().min(2),
      phone: z.string().min(10),
    }),
    branchId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid branch ID').optional(),
    costCenterId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid cost center ID').optional(),
    primaryManagerId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid manager ID').optional(),
    designationId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid designation ID').optional(),
    departmentId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid department ID').optional(),
    confirmationDate: z.string().optional(),
    terminationDate: z.string().optional(),
    bankDetails: z.object({
      bankName: z.string().optional(),
      accountName: z.string().optional(),
      accountNumber: z.string().optional(),
      ifscCode: z.string().optional(),
      branchName: z.string().optional(),
    }).optional(),
    taxDetails: z.object({
      panNumber: z.string().optional(),
      taxRegime: z.enum(['OLD', 'NEW', '']).optional(),
    }).optional(),
    candidateId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid candidate ID').optional(),
    leadId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid lead ID').optional(),
  }),
});

export const updateEmployeeSchema = z.object({
  body: z.object({
    employeeCode: z.string().min(2).optional(),
    fullName: z.string().min(3).optional(),
    email: z.string().email().optional(),
    phone: z.string().min(10).optional(),
    department: z.string().min(2).optional(),
    designation: z.string().min(2).optional(),
    joiningDate: z.string().optional(),
    salary: z.number().min(0).optional(),
    address: z.string().min(5).optional(),
    profileImage: z.string().optional(),
    emergencyContact: z.object({
      name: z.string().min(2).optional(),
      relationship: z.string().min(2).optional(),
      phone: z.string().min(10).optional(),
    }).optional(),
    isActive: z.boolean().optional(),
    isLoginApproved: z.boolean().optional(),
    branchId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid branch ID').optional(),
    costCenterId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid cost center ID').optional(),
    primaryManagerId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid manager ID').optional(),
    designationId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid designation ID').optional(),
    departmentId: z.string().regex(/^[0-9a-fA-F]{24}$/, 'Invalid department ID').optional(),
    confirmationDate: z.string().optional(),
    terminationDate: z.string().optional(),
    bankDetails: z.object({
      bankName: z.string().optional(),
      accountName: z.string().optional(),
      accountNumber: z.string().optional(),
      ifscCode: z.string().optional(),
      branchName: z.string().optional(),
    }).optional(),
    taxDetails: z.object({
      panNumber: z.string().optional(),
      taxRegime: z.enum(['OLD', 'NEW', '']).optional(),
    }).optional(),
  }),
});
